### ISSUE TITLE
Crash when changing permission 

### ISSUE THREAD

**Issue by yehya73** [somia/ninchat-sdk-android#100]
Pixel / Android 9
Build: 0.0.4 SDK
Preconditions: Permissions for for the to use Camera / microphone and storage is giving
To reproduce:
User start a chat
Doctor accept
User go to app permissions on deny microphone and video (user don't want to use video call)
User go back to app
Expected result: user should be able to continue chat
Actual result: App crashes

**Comment by Toni-** [comment]
Related to #74
