### ISSUE TITLE
Pressing device back button on Etäasiointi view closes the app

### ISSUE THREAD

**Issue by yehya73** [somia/ninchat-sdk-android#105]
Android 6 / 7 / 9
Devices: Honor lite 7 / Edge s6 / Pixel
To Reproduce:

1. Login
2. Press back button on your device
Expected result: nothing happens (or at least the user should not be logged out)
Actual result: the app closes and when open again then the user need to login

**Comment by Toni-** [comment]
Not related to the SDK
