### ISSUE TITLE
Video consent avatar is pixelated

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#17]
Even if the asset is supposed to be vector, at least in Axels emulator the avatar was shown pixelated like upscaled bitmap.

**Comment by JussiPekonen-Qvik** [comment]
This is a by-product of the requirement of having a round image for avatars. I will investigate how I could avoid this issue with the 3rd-party library that is needed to fulfil the round avatar requirement.

**Comment by JussiPekonen-Qvik** [comment]
Fixed. Also, now the SDK has one dependency less than before.
