### ISSUE TITLE
You are next translation shows position in queue instead of queue name

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#24]
"Joined audience queue {{audienceQueue.queue_attrs.name}}, you are next."
is displayed as
<img width="315" alt="screenshot 2018-11-20 at 21 23 33" src="https://user-images.githubusercontent.com/1185899/48797339-916b8a00-ed0a-11e8-8080-f9308b253b72.png">

**Comment by JussiPekonen-Qvik** [comment]
Fixed.
