### ISSUE TITLE
Rating view does not have translations

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#27]
See screenshot. Translation keys should be used with "Skip", "Good", "Okay", and "Poor"
<img width="293" alt="screenshot 2018-11-20 at 22 05 59" src="https://user-images.githubusercontent.com/1185899/48799732-97fd0000-ed10-11e8-9da5-1c29e5687169.png">

**Comment by JussiPekonen-Qvik** [comment]
Fixed.
