### ISSUE TITLE
Close chat confirmation modal does not have translations

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#28]
"Close chat" and "Continue chat" translation keys should be used.
Main text ("Are you sure you..") should come from "closeConfirmText" string in site config if set.
<img width="296" alt="screenshot 2018-11-20 at 22 08 06" src="https://user-images.githubusercontent.com/1185899/48799912-f5914c80-ed10-11e8-96e0-22be32d8e456.png">

**Comment by JussiPekonen-Qvik** [comment]
Fixed.
