### ISSUE TITLE
Conversation ended text on backlog should be centered

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#31]
it is not

**Comment by JussiPekonen-Qvik** [comment]
On some devices it is, on others it is not.

**Comment by JussiPekonen-Qvik** [comment]
I would recommend that if the chat ended text is fairly long it is split into 2 (or more) lines in advance.

**Comment by JussiPekonen-Qvik** [comment]
Found the issue. Fixed.
