### ISSUE TITLE
Sometimes when agent sends a message the app crashes

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#32]
![screenshot 2018-11-27 at 15 01 26](https://user-images.githubusercontent.com/1185899/49083529-91611200-f255-11e8-9bd0-52a1b0d02fd7.png)
![screenshot 2018-11-27 at 15 02 31](https://user-images.githubusercontent.com/1185899/49083532-92923f00-f255-11e8-8dfb-4b7becf1cf9c.png)

**Comment by plokk** [comment]
Toni Kajantola reproduced this: "Jussi: Terveystalon tuotanto chat kaatui: Androidilla, klo n.13.05 Lääkäri-chat 24/7. ehdimme viestimään kertaalleen mutta kun lääkäri lähti kirjoittamaan toista viestiä meidän sovellus kaatui. (ei saatu stacktracea kiinni kun näytönsäästäjä meni päälle ja login lähetys hävis)"

**Comment by JussiPekonen-Qvik** [comment]
I was able to reproduce.

**Comment by JussiPekonen-Qvik** [comment]
Fixed.
