### ISSUE TITLE
Text area does not open without multiple finger taps in different coordinates

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#34]
Cursor blinks but keyboard does not open without fiddling and tapping with fingers

Google Pixel Android 9 API 28
SDK: 0.2.5

**Comment by JussiPekonen-Qvik** [comment]
Cannot reproduce. I will test on Android 9 device tomorrow when I have access to one.

**Comment by JussiPekonen-Qvik** [comment]
Fixed.
