### ISSUE TITLE
Spacing with attachment images is sometimes zero to speech bubbles

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#35]
Eg. 
1. Write text (speech bubble appears)
2. Upload attachment
-> zero spacing between attachment image and speech bubble

Google Pixel Android 9 API 28
SDK: 0.2.5

**Comment by JussiPekonen-Qvik** [comment]
Actually the image is not inside the bubble for some reason. Will investigate why the image loading library does that.

**Comment by JussiPekonen-Qvik** [comment]
Android seems to have a bug. When the layout inside a bubble has only an image, the size of the layout is sometimes reported as 0x0 when setting the bubble background. This can be worked around by adding the bubble background to the the image. However, when the size of the layout is not returned as 0x0, the image will have double padding. Maybe we can live with that.
