### ISSUE TITLE
On screen keyboard does not close properly

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#39]
Tried tapping backlog etc. but the keyboard didn't like to close

Google Pixel Android 9 API 28
SDK: 0.2.5

**Comment by JussiPekonen-Qvik** [comment]
There is no platform convention regarding this. I tested with few other chat/messaging apps and they do not dismiss the keyboard when tapping outside the message writing box.

Is the desired behaviour that the keyboard gets dismissed when the user taps outside the writing box?

**Comment by plokk** [comment]
How the keyboard is dismissed then? In iOS it is common that tapping outside keyboard the keyboard gets dismissed. This is desired behavior, since it seems that there isn't another obvious way to dismiss keyboard.

**Comment by JussiPekonen-Qvik** [comment]
On Android you can always dismiss the keyboard with the back button. That works, or at least should work, on every app that requires keyboard usage.

**Comment by plokk** [comment]
Ok. If this is the case, let's not do anything regarding this matter now.
