### ISSUE TITLE
Huge pixels in writing indicator

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#42]
Writing indicator animation is scaled way too big.

Google Pixel Android 9 API 28
SDK: 0.2.5

**Comment by huuki** [comment]
This could be on me. We could do a new one, if it can't be scaled down(?).

**Comment by JussiPekonen-Qvik** [comment]
It can be scaled down. We just never had a chat how tall it should be in the first place. :)

**Comment by JussiPekonen-Qvik** [comment]
Forced the size to be 40x20 as on iOS.
