### ISSUE TITLE
Erratic backlog behavior

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#43]
After fiddling with simultaneous writing indicators, when message was received backlog scrolled in wrong direction. An attachment was uploaded before. Might have something to do with it.

After starting chat nothing was shown in backlog. Apparently this has something to do with starting a new chat after finishing one.

After sending three message in a row doctors avatar (agentAvatar: true) disappeared from the backlog. This might have something to do with avatar going partially outside from the top of the screen. Eg. scrolling away from backlogs viewport.

Google Pixel Android 9 API 28
SDK: 0.2.5

**Comment by JussiPekonen-Qvik** [comment]
1. What is the desired behaviour when there are more than 1 agent in the discussion and all agents are writing a message?
2. It was requested that a new chat is always started. Is this now the wrong behaviour?
3. Haven't observed this behaviour myself. Needs testing.

**Comment by plokk** [comment]
1. Displaying the actual writing indicators works as they are supposed to work. The desired behavior would be that the backlog scrolls to the bottom after a new message is received. The problem is that backlog scrolling jumped upward maybe half the screen length which is not related to anything logical. This might have something to do with the backlog scrolling algorithm since it seems to cause all kinds of weird behavior.

2. The problem is that when a new chat is started, even if somebody sends a message it is not shown on the backlog. The backlog remains completely empty: no "Conversation has started or anything" is displayed besides the textarea and background graphic.

3. I was able to reproduce this with Google Pixel emulator running Android 7.0 and with a real Google Pixel running Android 9.0
<img width="222" alt="screenshot 2018-12-12 at 10 04 49" src="https://user-images.githubusercontent.com/1185899/49855320-841b5a00-fdf5-11e8-840b-3cac13c83270.png">
<img width="278" alt="screenshot 2018-12-12 at 10 05 07" src="https://user-images.githubusercontent.com/1185899/49855321-841b5a00-fdf5-11e8-8371-ca8fa75665ca.png">

**Comment by JussiPekonen-Qvik** [comment]
1. Ok. I need to test this myself. But the logic should be that the message backlog always scrolls to the bottom no matter what. I believe this could be related to the image issue reported in #35 and #36.
2. Hmm… This is most likely a test application issue that caused this. Will fix it there.
3. I was able to reproduce this too. For some reason the first message's avatar get cleared. I will investigate.

**Comment by JussiPekonen-Qvik** [comment]
1. Fixed by #35 (and #36).
2. Test application has been fixed.
3. Fixed.
