### ISSUE TITLE
User name is not displayed in agent view

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#58]
User name should be derived from "userName" in config and set as user_attrs.name. Exists in 0.4.0

<img width="331" alt="Screenshot 2019-09-09 at 10 26 10" src="https://user-images.githubusercontent.com/1185899/64511119-4e57c300-d2ec-11e9-9742-aba933d05016.png">

**Comment by JussiPekonen-Qvik** [comment]
The session was created before fetching the configuration, therefore the user name was missing and was not set. Now the session is created after the configuration fetch.
