### ISSUE TITLE
Android 9 SDK 0.4.3: Video can be started only once, before erratic behaviour occurs

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#61]
Video conversation can be done successfully only once. After eg. agent ends video conversation and starts it again, video invitation pipeline seems to work correctly, but after that video streams don't work both ways and customers screen shows video loading indicator with video stream. Looks like something is out of sync.

**Comment by JussiPekonen-Qvik** [comment]
This is caused by some funkiness in the WebRTC library. The call teardown seems to make the library go to a state where a new call cannot be initiated for some reason. Needs time for investigation.
