### ISSUE TITLE
Video does not rotate correctly based on phones rotation

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#65]
Apparently this issue can not be reproduced in 0.4.1

When phone is rotated to left (to horizontal) video is correctly turned to full screen and horizontal. When phone is rotated to right (to vertical), video is not turned back from full screen.

The other direction works as expected.

It seems this works correctly with Android 6 but not in Android 9

**Comment by JussiPekonen-Qvik** [comment]
The SDK relies on the phone orientation configuration change triggered by the OS. If that does not get triggered, then there is nothing the SDK can do here. However, if the user has tapped the fullscreen button, the video is shown fullscreen horizontally and the configuration change triggers are ignored.
