### ISSUE TITLE
Retransfer issue (has never arrived in the actual queue)

### ISSUE THREAD

**Issue by yehya73** [somia/ninchat-sdk-android#96]
SDK: 0.4.4
Android 6 / 7 / 9
Devices: Honor lite 7 / Samsung Galaxy S6 / Huawei P20 Lite
To reproduce:
Patient open chat
Doctor answer and transfer 
Doctor answer the Patient and retransfer
the user see the spinner on his view. but he is not in any queue anymore.

**Comment by Toni-** [comment]
Related to #81
